# 接口测试，生成Token的用户名、密码。使用自己账号注意跟要平常用的账号分开，否则自动化时会被T掉。
beta : #beta环境
    NORMAL : #业主端，默认账号
        user_name : 13888888888
        password : 123456
    NORMAL_XIAOMEI : #业主端，小梅
        user_name : 13888888888
        password : 123456
    NORMAL_YAOYAO : #业主端，瑶瑶
        user_name : 13636075013
        password : cy123456
    SUPPLIER : #供应商，默认账号
        user_name : autotest01
        password : 123456
    MANAGER : #运营后台，默认账号
        user_name : autotestmanager01
        password : 123456
    PMMANAGER : #物业后台，默认总部账号
        user_name : 18600002001
        password : 123456
    PMMANAGER_COMMUNITY : #物业后台，默认小区账号
        user_name : 18600002001
        password : 123456
    STAFF : #员工端，默认账号
        user_name : 13660394444
        password : 123456

fix : #fix环境
    NORMAL : #业主端
        user_name : 13888888888
        password : 123456
    SUPPLIER : #供应商
        user_name : autotest01
        password : 123456
    MANAGER : #运营后台
        user_name : autotestmanager01
        password : 123456