#接口测试，数据库环境
beta : #beta环境
    host : 10.100.163.4
    port : 3301
    user_name : dev_user
    password : dev_user123

fix : #fix环境
    host : 10.100.163.5
    port : 3301
    user_name : dev_user
    password : dev_user123